Claim Pallet
zkVerify/zkVerify pull request #201
Opened 2024-12-23 14:59 UTC by DanieleDiBenedetto

This PR introduces pallet implementing the possibility of making airdrops on-chain and letting **Beneficiaries**
manually claim the amount of tokens they have right to.

- Only **ManagerOrigin** is able to start and end airdrops, as well as adding and removing beneficiaries with their rightful balance.
- Currently it possible only to held one airdrop at a time.
- When airdrop ends, all the funds still available in the pallet's associated account are transferred to **UnclaimedDestination**.

2025-01-10 12:00 UTC, drgora commented on pallets/claim/src/lib.rs
> +                    }
If I'm understanding the logic correctly, I believe this check should be done out of the loop, as it may temporarily fail (while it shouldn't) during the iterations.

Also, I'm wondering whether it would make sense to make this entire function atomic: either it succeeds and `Beneficiaries` is updated, or it fails and the state is not changed at all.

2025-01-10 16:30 UTC, drgora requested changes
I'm not sure that allowing the execution of `do_add_beneficiaries` while the airdrop is active is safe. The expected interaction is not clear, and a different order of the extrinsics might result in unexpected and unwanted behaviors.

For example, consider the following scenario:
```
add_beneficiaries(addr1, 1000);
claim_for(addr1);
add_beneficiaries(addr1, 2000);
```
This might even be a legit scenario, but what if the second call to `add_beneficiaries` was only meant to update the airdrop for `addr1` from `1000` to `2000`, instead of assigning a total of `3000`?
This dependency on the order of the extrinsics is undesirable. I guess we might consider adding a `paused` state for the airdrop, and restrict any beneficiary manipulation to be executed only in a paused state? Or else, we could forbid updating existing entries in the beneficiary list altogether?

2025-01-10 17:02 UTC, DanieleDiBenedetto commented on pallets/claim/src/lib.rs
> +                    }
This is a good point indeed, but honestly I don't envision any of the add/remove beneficiaries being ever called after having added beneficiaries the first time. On top of this, considering they could only be called by a Super User or Treasury, we can safely assume that they won't be that frequent/superficial to cause this kind of issues.
I already felt overdesigning with these mechanisms, and thus I don't feel complicating the logic furthermore for something that will likely never happen.
But I'm happy to discuss further you think it's indeed worth the effort :)

2025-01-10 17:03 UTC, 95DDB commented
@drgora  This is a good point indeed, but honestly I don't envision any of the add/remove beneficiaries being ever called after having added beneficiaries the first time. On top of this, considering they could only be called by a Super User or Treasury, we can safely assume that they won't be that frequent/superficial to cause this kind of issues.
I already felt overdesigning with these mechanisms, and thus I don't feel complicating the logic furthermore for something that will likely never happen.
But I'm happy to discuss further you think it's indeed worth the effort :)

2025-01-10 17:04 UTC, DanieleDiBenedetto commented on pallets/claim/src/lib.rs
> +                    }
Extrinsic execution should already be atomic: if it fails in the middle of the execution, the state will stay untouched

2025-01-10 17:15 UTC, drgora commented on pallets/claim/src/lib.rs
> +                    }
Right, the atomicity is guaranteed by the framework, makes sense. But I still believe the first point should be addressed: in the current state, the update might fail even if it is correct.
For example, imagine having a pot of `10`, distributed like `(addr1, 5), (addr2, 5)`; updating that to `(addr1, 6), (addr2, 4)` might fail with `NotEnoughFunds`, depending on the order of the beneficiaries map.

2025-01-10 17:23 UTC, drgora commented
> @drgora This is a good point indeed, but honestly I don't envision any of the add/remove beneficiaries being ever called after having added beneficiaries the first time.

I agree, so maybe we can just remove it?

> On top of this, considering they could only be called by a Super User or Treasury, we can safely assume that they won't be that frequent/superficial to cause this kind of issues.

I believe this is not an issue of being superficial, and might be actually open room for attacks: a malicious (or just lucky) beneficiary, might be able to observe the `add_beneficiaries` extrinsic in the mempool, before it is added to a block. If she manages to front-run that with her `claim` extrinsic, she might be able to obtain more tokens than intended.

2025-01-10 17:30 UTC, DanieleDiBenedetto commented on pallets/claim/src/lib.rs
> +                    }
Ah right, good catch !

2025-01-10 17:32 UTC, 95DDB commented
> > @drgora This is a good point indeed, but honestly I don't envision any of the add/remove beneficiaries being ever called after having added beneficiaries the first time.
> 
> I agree, so maybe we can just remove it?
> 
> > On top of this, considering they could only be called by a Super User or Treasury, we can safely assume that they won't be that frequent/superficial to cause this kind of issues.
> 
> I believe this is not an issue of being superficial, and might be actually open room for attacks: a malicious (or just lucky) beneficiary, might be able to observe the `add_beneficiaries` extrinsic in the mempool, before it is added to a block. If she manages to front-run that with her `claim` extrinsic, she might be able to obtain more tokens than intended.

So you're basically proposing to allow adding beneficiaries only in the context of beginning a new airdrop, and only let removing them afterwards.
Although, even in case of removing, one could front-run the extrinsic and claim its tokens before it gets removed.
So, per your suggestions, there are two paths here: 
- Keep add/remove beneficiaries but allow it only during a "Paused" state like you suggested but it would really become over-designed at that point (theoretically one could front-run the extrinsic that would put the state in "Paused" as well...)
- Remove the "remove_beneficiaries" and keep "add_beneficiaries" but it won't be possible to modify already existing beneficiaries' amounts (I could indeed see a situation in which we might want to add a new beneficiaries and don't want to wait for the next airdrop. Well, we could introduce the possibility of managing multiple airdrops but again, at the moment, it feels like overdesign)

2025-01-13 14:32 UTC, drgora commented
>     * Remove the "remove_beneficiaries" and keep "add_beneficiaries" but it won't be possible to modify already existing beneficiaries' amounts (I could indeed see a situation in which we might want to add a new beneficiaries and don't want to wait for the next airdrop. Well, we could introduce the possibility of managing multiple airdrops but again, at the moment, it feels like overdesign)

I totally agree on this, forbidding any modification to existing allocations (besides zeroing them) seems like a simple yet effective solution.

2025-01-21 09:29 UTC, drgora approved these changes
LGTM, I just left few comments here and there, none of which should be a blocker

2025-01-21 09:29 UTC, drgora commented on pallets/claim/src/benchmarking.rs
> +        // Worst case scenario: all the amounts of existing beneficiaries have been modified
It looks like this comment can be removed?

2025-01-21 10:06 UTC, DanieleDiBenedetto commented on pallets/claim/src/benchmarking.rs
> +// Copyright 2024, Horizen Labs, Inc.
@lgiussan

2025-01-23 17:04 UTC, lgiussan commented on pallets/claim/src/benchmarking.rs
> +// Copyright 2024, Horizen Labs, Inc.
If it's doable, I would sugegst yes

2025-01-27 10:16 UTC, la10736 commented on pallets/claim/Cargo.toml
> +log = "0.4.20"
Maybe could be a a nice idea to start to move all crates dependency (at least the common ones) in the workspace Cargo.toml.

What do you think?

2025-01-27 10:24 UTC, la10736 commented on pallets/claim/src/lib.rs
> +    #[pallet::getter(fn beneficiaries)]
You can remove all getter: are unused

2025-01-27 10:48 UTC, la10736 commented on pallets/claim/src/lib.rs
> +        >;
Maybe you don't need this abstraction at all. Indeed, it's nice, but you cannot use this abstraction to inspect the account and to move founds in. Moreove this can be not coherent with the pallet `account_id` used to check the ballance and move the unclaimed founds.

2025-01-27 10:50 UTC, la10736 commented on pallets/claim/src/lib.rs
> +        pub fn account_id() -> T::AccountId {
According to the comment save it in a storage value to not recompute it every time ... or remove the comment.

2025-01-27 14:44 UTC, la10736 commented on pallets/claim/src/lib.rs
> +                            .map_err(|_| Error::<T>::PayoutError)?;
Again, maybe is better to remove `Paymaster` abstraction because here you didn't have any assurance that the Paymaster have enough founds.

2025-01-27 14:45 UTC, la10736 commented on pallets/claim/src/lib.rs
> +                            *required_amount = required_amount.saturating_sub(*amount)
Use the `defensive` variation instead

2025-01-27 14:46 UTC, la10736 commented on pallets/claim/src/lib.rs
> +        AlreadyStarted,
```suggestion
        /// Attempt to start a new airdrop while there is one already in progress
```

2025-01-27 14:51 UTC, la10736 commented on pallets/claim/src/lib.rs
> +                            Err(Error::<T>::PayoutError)?; // Prevent going under the existential deposit of the account
Here you can use the substrate's `TokenError:FundsUnavailable` error instead

2025-01-27 14:53 UTC, la10736 commented on pallets/claim/src/lib.rs
> +                        required_amount = required_amount.saturating_add(*amount);
again, use defensive variation instead

2025-01-27 14:55 UTC, la10736 commented on pallets/claim/src/lib.rs
> +                        // Account already exists
```suggestion
                    if Beneficiaries::<T>::contains_key(account) {
```

2025-01-27 15:01 UTC, la10736 commented on pallets/claim/src/lib.rs
> +                        log::warn!("Beneficiary {account:?} with nothing to claim.");
Use guard approach instead:

```rust
if Beneficiaries::<T>::contains_key(account) {
    // Account already exists
    log::warn!("Beneficiary {account:?} already added.");
    Err(Error::<T>::AlreadyPresent)?;
} 
if amount.is_zero() {
    // Attempting to add a beneficiary with nothing to claim
    log::warn!("Beneficiary {account:?} with nothing to claim.");
    Err(Error::<T>::NothingToClaim)?;
}
// Account doesn't exist. Add its token amount to the required amount this pallet's account should have
required_amount = required_amount.saturating_add(*amount);
log::trace!("Added beneficiary {account:?}. Can claim: {amount:?}");
```

It's not _structured_ programming but is nicer and more clear to understand: the business logic is in the main branch code

2025-01-27 15:23 UTC, la10736 commented on pallets/claim/src/lib.rs
> +            beneficiaries: Option<BTreeMap<T::AccountId, BalanceOf<T>>>,
I'm proposing to remove the option here because I cannot see any advantage on call this function with `None` instead of using an empty map. If you're _scared_ by the `do_add_beneficiaries()` call you can put a guard at the `do_add_beneficiaries()` first line to exit if the map is empty and save two storage read.

This change also should simplify the benchmarks.

2025-01-27 15:42 UTC, la10736 commented on pallets/claim/src/lib.rs
> +            Ok(PostDispatchInfo {
```
Ok(Pays::No.into())
```
Do the job

2025-01-27 15:45 UTC, la10736 commented on pallets/claim/src/lib.rs
> +pub struct ClaimAccountId<R>(PhantomData<R>);
You didn't test this public struct

2025-01-27 15:55 UTC, la10736 commented on pallets/claim/src/tests.rs
> +    test_with_configs(
```suggestion
fn new_airdrop_insufficient_funds() {
```

2025-01-27 16:27 UTC, la10736 commented on pallets/claim/src/tests.rs
> +        assert_err!(
`assert_nop!` checks that you have an error **and** the storage not change: that's enough to check everything.

2025-01-27 16:32 UTC, la10736 commented on pallets/claim/src/tests.rs
You have a great coverage (91%) but I saw some issue here

1. You didn't test the _No pay_ feature anymore that is a business requirement
2. Too much assert in tests: ideally a (unit) tests should have just one assert per test.
3. In the negative tests you can leverage on `assert_nop` that also checks that the storage doesn't change. I put a comment in one of them, but is quite general.
4.

2025-01-27 16:37 UTC, la10736 commented on pallets/claim/src/benchmarking.rs
> +    fn begin_airdrop_empty_beneficiaries() {
You can remove it

2025-01-27 16:41 UTC, la10736 requested changes
Just some minor changes (no critical) and almost about the style and not the logic.

2025-01-28 08:22 UTC, DanieleDiBenedetto commented on pallets/claim/src/benchmarking.rs
> +// Copyright 2024, Horizen Labs, Inc.
will do in another PR, thanks !

2025-01-28 10:29 UTC, DanieleDiBenedetto commented on pallets/claim/src/lib.rs
> +            // TODO: Shall we want to withdraw all the balance in the pallet's account or only up to
@la10736 any opinion on this ?

2025-01-29 10:36 UTC, la10736 commented on pallets/claim/src/lib.rs
> +        pub fn account_id() -> T::AccountId {
define
```rust
    #[pallet::storage]
    pub type AccountId<T: Config> = StorageValue<_, T::AccountId>;
```
now you can use
```rust
    AccountId::<T>::mutate(|v| {
        let id = v.unwrap_or_else(|| T::PalletId::get().into_account_truncating());
        if v.is_none() {
            *v = Some(id.clone());
        }
        id
    })
```
I don't know if there is a simpler way to do it... If I'm not remember wrong I saw it implemented in a better way in pallet-timestamp or pallet-autority

2025-01-29 10:48 UTC, la10736 commented on pallets/claim/src/lib.rs
> +        pub fn account_id() -> T::AccountId {
I took a look to `pallet_authorship` and it implements like follow:

```rust
		// Check the memorized storage value.
		if let Some(id) = AccountId::<T>::get() {
			return id
		}

		let id = T::PalletId::get().into_account_truncating();
        AccountId::<T>::put(&id);
        id
```

2025-01-29 11:14 UTC, la10736 approved these changes
LGTM

2025-01-29 11:15 UTC, merged